export const OFFICIAL_LOGOS: Record<string, string> = {
  samsung: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Samsung_logo_wordmark.svg',
  apple: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
  xiaomi: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Xiaomi_logo_%282021-%29.svg',
  realme: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Realme_logo.svg',
  tecno: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Tecno_Mobile_logo.svg',
  infinix: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Infinix_logo.svg',
  oneplus: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/OnePlus_logo.svg',
  oppo: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/OPPO_LOGO_2019.svg',
  vivo: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Vivo_logo_2019.svg',
  huawei: 'https://upload.wikimedia.org/wikipedia/commons/d/db/Huawei_wordmark_2019.svg',
  motorola: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Motorola_new_logo.svg',
  honor: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Honor_Logo_%282020%29.svg',
  nokia: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Nokia_2023.svg',
  google: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
  nothing: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Nothing.svg',
  'google pixel': 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
};