'use client';
import { readApiResponse } from '@/lib/client/api-response';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ImageIcon, RefreshCw, ShieldAlert, Images, Copy, Accessibility, CheckCircle2, XCircle, ExternalLink } from 'lucide-react';

type Signal = {
  _id: string; type: string; severity: 'info'|'warning'|'critical'; status: 'open'|'resolved'|'dismissed';
  title: string; details: string; recommendedValue?: string | null; lastSeenAt: string;
  phoneId?: { _id: string; modelName: string; slug: string; status: string; thumbnail?: string };
  imageId?: { _id: string; url: string; altText?: string; role?: string; color?: string } | null;
};
type Payload = { items: Signal[]; total: number; page: number; pages: number; summary: { openSignals: number; phonesWithoutImages: number; missingAlt: number; duplicates: number } };

const LABELS: Record<string,string> = {
  missing_all_images:'Missing all images', missing_thumbnail:'Missing thumbnail', insecure_thumbnail:'Insecure thumbnail',
  invalid_image_url:'Invalid URL', insecure_image_url:'Insecure image URL', missing_alt_text:'Missing alt text',
  duplicate_image:'Duplicate image', thumbnail_not_in_gallery:'Thumbnail outside gallery',
};
const APPLY_TYPES = new Set(['missing_thumbnail','insecure_thumbnail','missing_alt_text','insecure_image_url','duplicate_image','invalid_image_url','thumbnail_not_in_gallery']);

export default function ImageIntelligencePage() {
  const [data,setData]=useState<Payload|null>(null); const [loading,setLoading]=useState(true); const [running,setRunning]=useState(false);
  const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [status,setStatus]=useState('open'); const [type,setType]=useState('all'); const [page,setPage]=useState(1);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/admin/image-intelligence?status=${encodeURIComponent(status)}&type=${encodeURIComponent(type)}&page=${page}`,{credentials:'include',cache:'no-store'});const p=await readApiResponse(r);if(!r.ok)throw new Error(p.error||'Unable to load Image Intelligence');setData(p);}catch(e){setError(e instanceof Error?e.message:'Unable to load Image Intelligence');}finally{setLoading(false);}},[status,type,page]);
  useEffect(()=>{void load();},[load]);
  const run=async(action:string,id?:string)=>{setError('');setMessage('');if(action==='scan')setRunning(true);try{const r=await fetch('/api/admin/image-intelligence',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='scan'?{action,limit:150}:{action,id})});const p=await readApiResponse(r);if(!r.ok)throw new Error(p.error||'Action failed');setMessage(action==='scan'?`Scan complete: ${p.scannedPhones} phones checked, ${p.signalsSeen} signals reviewed.`:action==='apply'?'Recommendation applied.':'Signal dismissed.');await load();}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setRunning(false);}};
  const cards=useMemo(()=>data?[{label:'Open signals',value:data.summary.openSignals,icon:ShieldAlert,cls:'bg-amber-50 text-amber-700'},{label:'Phones without images',value:data.summary.phonesWithoutImages,icon:Images,cls:'bg-red-50 text-red-700'},{label:'Missing alt text',value:data.summary.missingAlt,icon:Accessibility,cls:'bg-blue-50 text-blue-700'},{label:'Duplicate images',value:data.summary.duplicates,icon:Copy,cls:'bg-violet-50 text-violet-700'}]:[],[data]);
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-900"><ImageIcon className="h-7 w-7 text-blue-600"/>Image Intelligence</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Low-load image quality center for missing images, duplicate URLs, HTTPS safety, thumbnails and accessibility. No paid AI and no automatic publishing.</p></div><button onClick={()=>void run('scan')} disabled={running} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${running?'animate-spin':''}`}/>{running?'Scanning…':'Scan 150 phones'}</button></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}
    {data&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(c=>{const Icon=c.icon;return <div key={c.label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`mb-4 inline-flex rounded-xl p-2.5 ${c.cls}`}><Icon className="h-5 w-5"/></div><div className="text-3xl font-bold text-slate-900">{c.value.toLocaleString()}</div><div className="mt-1 text-sm text-slate-500">{c.label}</div></div>;})}</div>}
    <div className="flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="open">Open</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option><option value="all">All statuses</option></select><select value={type} onChange={e=>{setType(e.target.value);setPage(1);}} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="all">All signal types</option>{Object.entries(LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><Link href="/admin/data-quality?tab=missing-images" className="ml-auto inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700"><Images className="h-4 w-4"/>Missing Images</Link></div>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-900">Image review queue</h2><p className="text-sm text-slate-500">Every change requires an admin click. Missing-image acquisition stays manual to avoid copyright and source-quality risks.</p></div><div className="divide-y divide-slate-100">{loading?<div className="p-8 text-center text-sm text-slate-500">Loading…</div>:!data?.items.length?<div className="p-8 text-center text-sm text-slate-500">No signals match this filter.</div>:data.items.map(s=><div key={s._id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-900">{s.phoneId?.modelName||'Unknown phone'}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${s.severity==='critical'?'bg-red-50 text-red-700':s.severity==='warning'?'bg-amber-50 text-amber-700':'bg-blue-50 text-blue-700'}`}>{s.severity}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{LABELS[s.type]||s.type}</span></div><div className="mt-2 text-sm font-medium text-slate-800">{s.title}</div><p className="mt-1 text-sm text-slate-500">{s.details}</p>{s.imageId?.url&&<a href={s.imageId.url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-blue-600">View image<ExternalLink className="h-3 w-3"/></a>}</div>{s.status==='open'&&<div className="flex shrink-0 gap-2">{APPLY_TYPES.has(s.type)&&<button onClick={()=>void run('apply',s._id)} className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white"><CheckCircle2 className="h-4 w-4"/>Apply</button>}<button onClick={()=>void run('dismiss',s._id)} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700"><XCircle className="h-4 w-4"/>Dismiss</button></div>}</div></div>)}</div>{data&&data.pages>1&&<div className="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-sm"><button disabled={page<=1} onClick={()=>setPage(v=>Math.max(1,v-1))} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Previous</button><span className="text-slate-500">Page {page} of {data.pages}</span><button disabled={page>=data.pages} onClick={()=>setPage(v=>Math.min(data.pages,v+1))} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Next</button></div>}</section>
    <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800"><b>Safety:</b> this module only analyzes saved metadata and URLs. It does not scrape images, call paid AI, download copyrighted files, or publish changes automatically.</div>
  </div>;
}
