'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { Header } from '@/components/shared/Header';
import { Footer } from '@/components/shared/Footer';

type Result = { phone: { slug: string; modelName: string; pricePKR: number; href: string; brand?: { name: string } }; matchPercentage: number; confidence: string; reasons: string[]; compromises: string[]; dataFreshness: string; missingData: string[] };
export default function BuyingAssistantPage() {
  const [query,setQuery]=useState(''); const [results,setResults]=useState<Result[]>([]); const [warnings,setWarnings]=useState<string[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError('');try{const response=await fetch('/api/buying-assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to search');setResults(data.results||[]);setWarnings(data.warnings||[]);}catch(value){setError(value instanceof Error?value.message:'Unable to search');}finally{setLoading(false)}}
  return <><Header/><main className="min-h-[70vh] bg-slate-50 px-4 py-10"><div className="mx-auto max-w-4xl"><h1 className="text-3xl font-extrabold">PhoneDock Buying Assistant</h1><p className="mt-2 text-slate-600">Ask in English or Roman Urdu. Recommendations use verified PhoneDock records and explain missing data.</p><form onSubmit={submit} className="mt-6 flex gap-2"><label className="sr-only" htmlFor="buying-query">Phone requirements</label><input id="buying-query" value={query} onChange={event=>setQuery(event.target.value)} required minLength={3} maxLength={300} placeholder="Best gaming mobile under 100 hazar with PTA" className="h-12 flex-1 rounded-xl border bg-white px-4"/><button disabled={loading} className="rounded-xl bg-blue-600 px-5 font-bold text-white disabled:opacity-60">{loading?'Checking...':'Recommend'}</button></form>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{warnings.map(item=><p key={item} className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{item}</p>)}<div className="mt-6 grid gap-4 sm:grid-cols-2">{results.map(item=><article key={item.phone.slug} className="rounded-2xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-slate-500">{item.phone.brand?.name}</p><h2 className="font-extrabold">{item.phone.modelName}</h2></div><span className="rounded-full bg-blue-50 px-2 py-1 text-sm font-bold text-blue-700">{item.matchPercentage}% match</span></div><p className="mt-2 font-bold text-blue-600">PKR {item.phone.pricePKR.toLocaleString()}</p><ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{item.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>{item.compromises.length>0&&<p className="mt-3 text-xs text-amber-700">Compromises: {item.compromises.join('; ')}</p>}{item.missingData.length>0&&<p className="mt-2 text-xs text-slate-500">Missing: {item.missingData.join(', ')}</p>}<p className="mt-2 text-xs text-slate-500">{item.dataFreshness} · confidence: {item.confidence}</p><Link href={item.phone.href} className="mt-4 inline-flex h-10 items-center rounded-xl bg-slate-900 px-4 text-sm font-semibold text-white">View phone</Link></article>)}</div></div></main><Footer/></>;
}
