import { NextRequest, NextResponse } from 'next/server';
import { ActivityLog, Phone, PhoneRetailListing, PriceIntelligenceSignal, PriceSource, PriceTrackerHistory } from '@/lib/models';
import { connectDB, getAdminFromRequest, requirePermission } from './helpers';
import { scanPriceIntelligence } from '@/lib/price-intelligence';
import { revalidatePublicContent } from '@/lib/revalidate';
export async function handlePriceIntelligenceV2Get(req:NextRequest):Promise<NextResponse>{const auth=await getAdminFromRequest(req);if(auth.error)return auth.error;const denied=requirePermission(auth.admin,'prices:read');if(denied)return denied;await connectDB();const status=req.nextUrl.searchParams.get('status')||'open';const type=req.nextUrl.searchParams.get('type')||'all';const page=Math.max(1,Number(req.nextUrl.searchParams.get('page')||1));const limit=Math.min(100,Math.max(10,Number(req.nextUrl.searchParams.get('limit')||30)));const filter:any={};if(status!=='all')filter.status=status;if(type!=='all')filter.type=type;const [items,total,open,critical,recommendations]=await Promise.all([PriceIntelligenceSignal.find(filter).sort({severity:1,lastSeenAt:-1}).skip((page-1)*limit).limit(limit).populate('phoneId','modelName slug pricePKR currentPrice manualLock').populate('sourceId','name baseUrl trusted enabled status').lean(),PriceIntelligenceSignal.countDocuments(filter),PriceIntelligenceSignal.countDocuments({status:'open'}),PriceIntelligenceSignal.countDocuments({status:'open',severity:'critical'}),PriceIntelligenceSignal.countDocuments({status:'open',type:'recommended_market_price'})]);return NextResponse.json({items,total,page,pages:Math.max(1,Math.ceil(total/limit)),summary:{open,critical,recommendations}},{headers:{'Cache-Control':'no-store'}})}
export async function handlePriceIntelligenceV2Post(req:NextRequest):Promise<NextResponse>{const auth=await getAdminFromRequest(req);if(auth.error)return auth.error;const denied=requirePermission(auth.admin,'prices:edit');if(denied)return denied;await connectDB();const body=await req.json().catch(()=>({}));const action=String(body.action||'');if(action==='scan'){const result=await scanPriceIntelligence({limit:Number(body.limit||25)});await ActivityLog.create({adminId:auth.admin._id,action:'price_intelligence_v2_scan',entityType:'price_intelligence',details:JSON.stringify(result)});return NextResponse.json({success:true,...result});}const id=String(body.id||'');if(!id)return NextResponse.json({error:'Signal id is required'},{status:400});const signal:any=await PriceIntelligenceSignal.findById(id);if(!signal)return NextResponse.json({error:'Signal not found'},{status:404});if(action==='dismiss'){signal.status='dismissed';signal.resolvedAt=new Date();signal.resolvedBy=auth.admin._id;signal.resolutionNotes=String(body.notes||'Dismissed by admin.');await signal.save();return NextResponse.json({success:true,signal});}if(action!=='apply')return NextResponse.json({error:'Unsupported action'},{status:400});
if(signal.type!=='recommended_market_price'||Number(signal.recommendedPrice)<=0||!signal.sourceId||!signal.sourceUrl)return NextResponse.json({error:'This signal has no verified actionable price recommendation'},{status:400});
const [source,listing]=await Promise.all([
 PriceSource.findOne({_id:signal.sourceId,enabled:true,trusted:true,status:'active'}).lean(),
 PhoneRetailListing.findOne({phoneId:signal.phoneId,sourceId:signal.sourceId,productUrl:signal.sourceUrl,enabled:true,verificationStatus:'verified',availability:'available',currentSourcePrice:{$gt:0}}).lean(),
]);
if(!source||!listing)return NextResponse.json({error:'The retailer source or exact listing is no longer trusted, verified, available, or active. Run the scan again.'},{status:409});
const listingPrice=Number(listing.currentSourcePrice||0),recommendedPrice=Number(signal.recommendedPrice||0);
if(!listingPrice||Math.abs(listingPrice-recommendedPrice)>1)return NextResponse.json({error:'The retailer price changed after this recommendation. Run the scan again before applying.'},{status:409});
const phone:any=await Phone.findById(signal.phoneId);if(!phone)return NextResponse.json({error:'Phone not found'},{status:404});if(phone.manualLock&&!body.force)return NextResponse.json({error:'Phone price is manually locked'},{status:409});const old=Number(phone.pricePKR||0),next=listingPrice;
if(old>0&&Math.abs(next-old)/old>0.35&&!body.force)return NextResponse.json({error:'Price differs by more than 35% from the current public price. Review the exact variant and submit again with force confirmation.'},{status:409});phone.previousPrice=old;phone.pricePKR=next;phone.currentPrice=next;phone.lowestPrice=!phone.lowestPrice?next:Math.min(phone.lowestPrice,next);phone.highestPrice=Math.max(Number(phone.highestPrice||0),next);phone.priceChange=next-old;phone.percentageChange=old?((next-old)/old)*100:0;phone.lastPriceCheckedAt=new Date();phone.lastPriceChangedAt=new Date();phone.preferredPriceSourceId=signal.sourceId||null;await phone.save();await PriceTrackerHistory.create({phoneId:phone._id,oldPrice:old,newPrice:next,difference:next-old,percentageChange:old?((next-old)/old)*100:0,changeType:next>old?'increase':next<old?'decrease':'unchanged',sourceType:'retailer',sourceId:signal.sourceId||null,sourceUrl:signal.sourceUrl||'',approvedByAdminId:auth.admin._id,verificationStatus:'confirmed',capturedAt:new Date()});signal.status='resolved';signal.resolvedAt=new Date();signal.resolvedBy=auth.admin._id;signal.resolutionNotes=String(body.notes||'Trusted market recommendation applied by admin.');await signal.save();await ActivityLog.create({adminId:auth.admin._id,action:'price_intelligence_v2_applied',entityType:'phone',entityId:phone._id,details:`PKR ${old} -> ${next}`});revalidatePublicContent();return NextResponse.json({success:true,signal});}
