import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const builder = fs.readFileSync(path.join(root, 'src/app/admin/homepage-builder/page.tsx'), 'utf8');
const layout = fs.readFileSync(path.join(root, 'src/app/admin/layout.tsx'), 'utf8');
const handler = fs.readFileSync(path.join(root, 'src/app/api/[[...path]]/handlers/admin-crud.ts'), 'utf8');
const homeContent = fs.readFileSync(path.join(root, 'src/app/HomeContent.tsx'), 'utf8');
const heroShowcase = fs.readFileSync(path.join(root, 'src/components/shared/HeroPhoneShowcase.tsx'), 'utf8');
const globalCss = fs.readFileSync(path.join(root, 'src/app/globals.css'), 'utf8');

assert.match(layout, /Homepage Builder', href: '\/admin\/homepage-builder'/, 'sidebar must open the Pro Builder');
assert.match(layout, /Site Settings', href: '\/admin\/settings'/, 'legacy settings must remain available as a safe fallback');
assert.match(builder, /draggable/, 'section rows must support drag ordering');
assert.match(builder, /onDrop/, 'section drag ordering must have a drop handler');
assert.match(builder, /aria-label=\{`Move \$\{LABELS\[key\]\} up`\}/, 'section ordering must retain an accessible keyboard fallback');
assert.match(builder, /brand: ''/, 'section rules must support brand filtering');
assert.match(builder, /year: ''/, 'section rules must support release-year filtering');
assert.match(builder, /lifecycle: ''/, 'section rules must support lifecycle filtering');
assert.match(builder, /priceMin: ''/, 'section rules must support price filtering');
assert.match(builder, /manualPhoneSlugs/, 'section rules must support manual phone selection');
assert.match(builder, /\['desktop', Monitor\]/, 'preview must offer desktop mode');
assert.match(builder, /\['tablet', Tablet\]/, 'preview must offer tablet mode');
assert.match(builder, /\['mobile', Smartphone\]/, 'preview must offer mobile mode');
assert.match(builder, /Design system/, 'builder must expose global design controls');
assert.match(builder, /Header & links/, 'builder must expose navigation controls');
assert.match(builder, /Media library/, 'builder must expose media controls');
assert.match(builder, /3D stage positioning/, 'builder must expose precise hero positioning');
assert.match(builder, /release-year categories/, 'builder must expose release-year category controls');
assert.match(builder, /uploadImage/, 'builder must support managed image uploads');
assert.match(handler, /revalidatePath\('\/admin\/homepage-builder'\)/, 'settings update must revalidate the Pro Builder');
assert.doesNotMatch(homeContent, /brands\.filter\(b => \(b\._count\?\.phones \|\| 0\) > 0\)/, 'brand navigation must not disappear when public phone counts are temporarily zero');
assert.match(homeContent, /'View brand'/, 'zero-count brands must retain useful navigation text');
assert.match(homeContent, /CURATED_BRAND_DIRECTORY/, 'homepage must retain a curated brand directory when MongoDB returns only a partial brand list');
assert.match(homeContent, /brandBySlug\.set/, 'database brands must merge into the curated directory instead of replacing it');
assert.match(homeContent, /isolate flex flex-col gap-5/, 'price and year panels must use an isolated flex stack that cannot overlap');
assert.match(homeContent, /renderOrderedSection\('latest'\)/, 'Latest Phones must fill the column below brands instead of leaving sidebar-height whitespace');
assert.match(homeContent, /filter\(key => key !== 'latest'\)/, 'Latest Phones must not render twice after moving into the brand column');
assert.match(heroShowcase, /failedImages/, 'hero must track failed remote phone images');
assert.match(heroShowcase, /window\.setTimeout\(next, 250\)/, 'hero must advance past a broken selected image');
assert.match(globalCss, /background: rgba\(240, 244, 248, 0\.94\)/, 'sticky header must be opaque enough to prevent hero text showing through it');

console.log('homepage-builder-pro: all assertions passed');
