import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const builder = fs.readFileSync(path.join(root, 'src/app/admin/homepage-builder/page.tsx'), 'utf8');
const layout = fs.readFileSync(path.join(root, 'src/app/admin/layout.tsx'), 'utf8');
const handler = fs.readFileSync(path.join(root, 'src/app/api/[[...path]]/handlers/admin-crud.ts'), 'utf8');
const homeContent = fs.readFileSync(path.join(root, 'src/app/HomeContent.tsx'), 'utf8');
const heroShowcase = fs.readFileSync(path.join(root, 'src/components/shared/HeroPhoneShowcase.tsx'), 'utf8');
const campaignBackground = fs.readFileSync(path.join(root, 'src/components/home/HeroCampaignBackground.tsx'), 'utf8');
const discoveryPanel = fs.readFileSync(path.join(root, 'src/components/home/HomeDiscoveryPanel.tsx'), 'utf8');
const globalCss = fs.readFileSync(path.join(root, 'src/app/globals.css'), 'utf8');

assert.match(layout, /Homepage Builder', href: '\/admin\/homepage-builder'/, 'sidebar must open the Pro Builder');
assert.match(layout, /Site Settings', href: '\/admin\/settings'/, 'legacy settings must remain available as a safe fallback');
assert.match(builder, /draggable/, 'section rows must support drag ordering');
assert.match(builder, /onDrop/, 'section drag ordering must have a drop handler');
assert.match(builder, /aria-label=\{`Move \$\{LABELS\[key\]\} up`\}/, 'section ordering must retain an accessible keyboard fallback');
assert.match(builder, /brand: ''/, 'section rules must support brand filtering');
assert.match(builder, /year: ''/, 'section rules must support release-year filtering');
assert.match(builder, /lifecycle: ''/, 'section rules must support lifecycle filtering');
assert.match(builder, /priceMin: ''/, 'section rules must support price filtering');
assert.match(builder, /manualPhoneSlugs/, 'section rules must support manual phone selection');
assert.match(builder, /\['desktop', Monitor\]/, 'preview must offer desktop mode');
assert.match(builder, /\['tablet', Tablet\]/, 'preview must offer tablet mode');
assert.match(builder, /\['mobile', Smartphone\]/, 'preview must offer mobile mode');
assert.match(builder, /Design system/, 'builder must expose global design controls');
assert.match(builder, /Header & links/, 'builder must expose navigation controls');
assert.match(builder, /Media library/, 'builder must expose media controls');
assert.match(builder, /3D stage positioning/, 'builder must expose precise hero positioning');
assert.match(builder, /Visible discovery tabs/, 'builder must expose unified discovery category controls');
assert.match(builder, /Discovery panel title/, 'builder must expose discovery presentation controls');
assert.match(builder, /View all button URL/, 'builder must expose the discovery destination');
assert.match(builder, /uploadImage/, 'builder must support managed image uploads');
assert.match(builder, /Seasonal background campaigns/, 'builder must expose scheduled seasonal hero campaigns');
assert.match(builder, /1920 × 760 px/, 'hero media controls must show recommended desktop dimensions');
assert.match(builder, /900 × 1200 px/, 'hero media controls must show recommended mobile dimensions');
assert.match(builder, /datetime-local/, 'campaigns must support start and end scheduling');
assert.match(handler, /homepage\.heroCampaigns = Array\.isArray/, 'campaign settings must be normalized server-side');
assert.match(handler, /slice\(0, 8\)/, 'campaign count must be bounded');
assert.match(campaignBackground, /isCampaignActive/, 'seasonal hero must respect campaign schedule windows');
assert.match(campaignBackground, /Math\.max\(4000, intervalMs\)/, 'background rotation must avoid aggressive performance-hostile intervals');
assert.match(handler, /revalidatePath\('\/admin\/homepage-builder'\)/, 'settings update must revalidate the Pro Builder');
assert.doesNotMatch(homeContent, /brands\.filter\(b => \(b\._count\?\.phones \|\| 0\) > 0\)/, 'brand navigation must not disappear when public phone counts are temporarily zero');
assert.match(homeContent, /'View brand'/, 'zero-count brands must retain useful navigation text');
assert.match(homeContent, /CURATED_BRAND_DIRECTORY/, 'homepage must retain a curated brand directory when MongoDB returns only a partial brand list');
assert.match(homeContent, /brandBySlug\.set/, 'database brands must merge into the curated directory instead of replacing it');
assert.match(homeContent, /HomeDiscoveryPanel/, 'homepage must render the unified discovery panel');
assert.match(discoveryPanel, /\/price-ranges/, 'price discovery must link to the working price-ranges page');
for (const query of ['priceCategory', 'ram', 'storage', 'camera', 'battery', 'pta', 'year']) {
  assert.match(discoveryPanel, new RegExp(`${query}=`), `discovery must provide a real ${query} filter link`);
}
assert.match(handler, /discoveryCategoryOrder/, 'discovery categories must be allowlisted server-side');
assert.match(handler, /homepage\.discoveryViewAllUrl = safeHref/, 'discovery destination must be sanitized server-side');
assert.match(layout, /AdminNavGroup/, 'admin navigation must be grouped into manageable sections');
assert.match(layout, /openNavSections/, 'admin navigation groups must be collapsible');
assert.match(homeContent, /renderOrderedSection\('latest'\)/, 'Latest Phones must fill the column below brands instead of leaving sidebar-height whitespace');
assert.match(homeContent, /filter\(key => key !== 'latest'\)/, 'Latest Phones must not render twice after moving into the brand column');
assert.match(heroShowcase, /validImageIds/, 'hero must track only phone images that successfully load');
assert.match(heroShowcase, /new window\.Image\(\)/, 'hero must preflight selected images before admitting their slides');
assert.match(heroShowcase, /naturalWidth >= 80/, 'hero must reject tiny placeholder images that create empty-looking slides');
assert.match(heroShowcase, /Publish each successful image immediately/, 'one slow remote image must not block all valid hero slides');
assert.doesNotMatch(heroShowcase, /Promise\.all\(phones\.map/, 'hero image validation must not deadlock behind one pending remote image');
assert.match(heroShowcase, /carouselPhones/, 'hero navigation must rotate through valid slides only');
assert.match(heroShowcase, /slideCount < 2/, 'hero autoplay must stop when fewer than two valid images exist');
assert.doesNotMatch(heroShowcase, /onMouseEnter=\{\(\) => setPaused\(true\)\}/, 'moving the pointer over the hero must not silently stop autoplay');
assert.match(heroShowcase, /Resume phone slideshow/, 'autoplay must provide an explicit accessible pause and resume control');
assert.doesNotMatch(heroShowcase, /<AnimatePresence mode="wait">\\s*<motion\.div\\s*key=\{phone/, 'the hero image must not deadlock behind an infinitely animated exiting stage');
assert.doesNotMatch(heroShowcase, /mix-blend-multiply/, 'hero product images must remain visible on the dark stage');
assert.match(heroShowcase, /mix-blend-normal/, 'hero product images must use stable normal compositing');
assert.match(heroShowcase, /featureCards/, 'premium dashboard must derive feature cards from real phone specifications');
assert.match(heroShowcase, /Detailed specifications will appear here when available/, 'premium dashboard must not fabricate missing specifications');
assert.match(homeContent, /aria-label="Popular phone categories"/, 'quick categories must expose an accessible navigation landmark');
assert.match(homeContent, /lg:justify-center/, 'quick categories must center as a group on desktop');
assert.match(globalCss, /background: rgba\(240, 244, 248, 0\.94\)/, 'sticky header must be opaque enough to prevent hero text showing through it');

console.log('homepage-builder-pro: all assertions passed');
