'use client';
import { readApiResponse } from '@/lib/client/api-response';
import { useCallback, useEffect, useState } from 'react';
import { RefreshCw, Check, X, ExternalLink, BadgeDollarSign } from 'lucide-react';

type Item={_id:string,status:string,severity:string,recommendedPrice?:number,sourceUrl?:string,[key:string]:any};
type Data={items:Item[];total:number;page:number;pages:number;summary:Record<string,number>};
type ActionResponse={error?:string;scannedPhones?:number;signalsSeen?:number;message?:string};
const EMPTY:Data={items:[],total:0,page:1,pages:1,summary:{}};

export default function PriceIntelligenceV2Page(){
 const [data,setData]=useState<Data>(EMPTY); const [selected,setSelected]=useState<Set<string>>(new Set());
 const [loading,setLoading]=useState(true); const [running,setRunning]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [status,setStatus]=useState('open'); const [page,setPage]=useState(1);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/admin/price-intelligence-v2?status=${status}&page=${page}`,{credentials:'include',cache:'no-store'});const p=await readApiResponse<Data>(r);setData(p);setSelected(new Set());}catch(e){setError(e instanceof Error?e.message:'Unable to load');}finally{setLoading(false);}},[status,page]);
 useEffect(()=>{void load();},[load]);
 const run=async(action:string,id?:string)=>{setRunning(id||action);setError('');setMessage('');try{const r=await fetch('/api/admin/price-intelligence-v2',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action,id})});const result=await readApiResponse<ActionResponse>(r);setMessage(result.message||`${action} completed.`);await load();}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setRunning('');}};
 const bulkDismiss=async()=>{const ids=Array.from(selected).slice(0,50);if(!ids.length||!confirm(`Dismiss ${ids.length} selected price signals?`))return;setRunning('bulk');setError('');setMessage('');let ok=0,failed=0;for(const id of ids){try{const r=await fetch('/api/admin/price-intelligence-v2',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action:'dismiss',id})});await readApiResponse<ActionResponse>(r);ok++;}catch{failed++;}}setMessage(`Bulk dismiss complete: ${ok} succeeded${failed?`, ${failed} failed`:''}.`);setRunning('');await load();};
 const openItems=data.items.filter(i=>i.status==='open');
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-900"><BadgeDollarSign className="h-7 w-7 text-emerald-600"/> Price Intelligence V2</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Pakistan retailer coverage, stale checks, price spread, history gaps and trusted market recommendations. No automatic public price changes.</p></div><button onClick={()=>void run('scan')} disabled={!!running} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${running==='scan'?'animate-spin':''}`}/>{running==='scan'?'Scanning…':'Scan now'}</button></div>
  <div className="grid gap-3 sm:grid-cols-3">{Object.entries(data.summary||{}).map(([k,v])=><div key={k} className="rounded-xl border bg-white p-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{k.replaceAll('_',' ')}</div><div className="mt-1 text-2xl font-bold">{v}</div></div>)}</div>
  {error&&<div className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{message}</div>}
  <div className="flex flex-wrap items-center gap-2 rounded-xl border bg-white p-3"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="rounded-lg border px-3 py-2 text-sm"><option value="open">Open</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option><option value="all">All</option></select><button onClick={()=>setSelected(new Set(openItems.map(i=>i._id)))} disabled={!openItems.length} className="rounded-lg border px-3 py-2 text-sm font-semibold disabled:opacity-40">Select page</button><button onClick={()=>setSelected(new Set())} disabled={!selected.size} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Clear</button><button onClick={()=>void bulkDismiss()} disabled={!selected.size||!!running} className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm font-semibold text-red-700 disabled:opacity-40">Dismiss selected ({selected.size})</button><span className="ml-auto text-xs text-slate-500">Bulk actions are capped at 50 records.</span></div>
  <div className="space-y-3">{loading?<div className="rounded-xl border bg-white p-8 text-center">Loading…</div>:data.items.length===0?<div className="rounded-xl border bg-white p-8 text-center text-slate-500">No signals found.</div>:data.items.map(item=>{const canApply=item.status==='open'&&Number(item.recommendedPrice||0)>0&&Boolean(item.sourceUrl);return <div key={item._id} className="rounded-xl border bg-white p-4"><div className="mb-3 flex items-center gap-2"><input type="checkbox" checked={selected.has(item._id)} disabled={item.status!=='open'} onChange={e=>setSelected(prev=>{const next=new Set(prev);e.target.checked?next.add(item._id):next.delete(item._id);return next})}/><span className="text-xs text-slate-500">Select for bulk action</span></div><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.severity==='critical'?'bg-red-100 text-red-700':item.severity==='warning'?'bg-amber-100 text-amber-700':'bg-blue-100 text-blue-700'}`}>{item.severity}</span><span className="text-xs text-slate-500">{item.field||item.type}</span></div><h2 className="mt-2 font-semibold text-slate-900">{item.title||item.phoneId?.modelName||'Price signal'}</h2><p className="mt-1 text-sm text-slate-600">{item.details||''}</p><div className="mt-2 text-xs text-slate-500">{item.phoneId?.modelName}{item.recommendedPrice?` • PKR ${Number(item.recommendedPrice).toLocaleString()}`:''}{item.sourceUrl&&<a className="ml-2 inline-flex items-center gap-1 text-blue-600" href={item.sourceUrl} target="_blank" rel="noreferrer">Retailer<ExternalLink className="h-3 w-3"/></a>}</div></div>{item.status==='open'&&<div className="flex gap-2"><button onClick={()=>void run('apply',item._id)} disabled={!!running||!canApply} title={!canApply?'A verified retailer URL and positive recommended price are required.':''} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40"><Check className="h-4 w-4"/>{canApply?'Apply':'Review source'}</button><button onClick={()=>void run('dismiss',item._id)} disabled={!!running} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-semibold text-slate-700"><X className="h-4 w-4"/>Dismiss</button></div>}</div></div>})}</div>
  <div className="flex items-center justify-between"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Previous</button><span className="text-sm text-slate-500">Page {data.page} of {data.pages}</span><button disabled={page>=data.pages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Next</button></div>
 </div>;
}
