import { db } from '../src/lib/db';
import { hash } from 'bcryptjs';

async function seed() {
  console.log('🌱 Seeding PhoneDock database...');

  // Create brands
  const brandData = [
    { name: 'Samsung', slug: 'samsung', logo: '/brands/samsung.svg', country: 'South Korea', description: 'South Korean multinational electronics corporation, the world\'s largest manufacturer of smartphones.', sortOrder: 1 },
    { name: 'Apple', slug: 'apple', logo: '/brands/apple.svg', country: 'USA', description: 'American multinational technology company known for the iPhone, the most premium smartphone brand in the world.', sortOrder: 2 },
    { name: 'Google', slug: 'google', logo: '/brands/google.svg', country: 'USA', description: 'American tech giant known for the Pixel line of smartphones with pure Android experience.', sortOrder: 3 },
    { name: 'Xiaomi', slug: 'xiaomi', logo: '/brands/xiaomi.svg', country: 'China', description: 'Chinese electronics company offering feature-rich smartphones at competitive prices, extremely popular in Pakistan.', sortOrder: 4 },
    { name: 'OnePlus', slug: 'oneplus', logo: '/brands/oneplus.svg', country: 'China', description: 'Chinese smartphone brand known for flagship killer devices with top-tier specs at reasonable prices.', sortOrder: 5 },
    { name: 'Vivo', slug: 'vivo', logo: '/brands/vivo.svg', country: 'China', description: 'Chinese technology company known for camera-focused smartphones and strong presence in South Asian markets.', sortOrder: 6 },
    { name: 'Oppo', slug: 'oppo', logo: '/brands/oppo.svg', country: 'China', description: 'Chinese consumer electronics brand focusing on camera technology and fast charging innovation.', sortOrder: 7 },
    { name: 'Realme', slug: 'realme', logo: '/brands/realme.svg', country: 'China', description: 'Chinese smartphone brand offering incredible value for money, very popular among Pakistani youth.', sortOrder: 8 },
    { name: 'Motorola', slug: 'motorola', logo: '/brands/motorola.svg', country: 'USA', description: 'American brand known for clean Android experience and durable smartphones with long battery life.', sortOrder: 9 },
    { name: 'Infinix', slug: 'infinix', logo: '/brands/infinix.svg', country: 'China', description: 'Budget-friendly smartphone brand with strong presence in Pakistan\'s entry-level and mid-range markets.', sortOrder: 10 },
    { name: 'Tecno', slug: 'tecno', logo: '/brands/tecno.svg', country: 'China', description: 'Transsion Holdings brand offering affordable smartphones tailored for emerging markets including Pakistan.', sortOrder: 11 },
    { name: 'Nothing', slug: 'nothing', logo: '/brands/nothing.svg', country: 'UK', description: 'London-based tech startup known for unique transparent design and clean Android experience.', sortOrder: 12 },
  ];

  for (const b of brandData) {
    await db.brand.upsert({ where: { slug: b.slug }, update: b, create: b });
  }
  console.log(`✅ ${brandData.length} brands created`);

  // Helper to get brand id
  const getBrandId = async (slug: string) => {
    const brand = await db.brand.findUnique({ where: { slug } });
    return brand!.id;
  };

  // Phone definitions (unique only)
  const phoneData = [
    { brandSlug: 'samsung', modelName: 'Galaxy S25 Ultra', slug: 'samsung-galaxy-s25-ultra', releaseDate: '2025-02-01', pricePKR: 425000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: true, description: 'Samsung\'s most powerful Galaxy S series phone with S Pen, AI features, and titanium build.', cameraScore: 96, performanceScore: 94, batteryScore: 88, displayScore: 97, valueScore: 72, overallRating: 4.5, sortOrder: 1,
      specs: { display: '6.9" Dynamic AMOLED 2X', resolution: '3120 x 1440', refreshRate: '120Hz', protection: 'Gorilla Armor 2', chipset: 'Snapdragon 8 Elite', cpu: 'Octa-core (4x4.47GHz + 4x3.53GHz)', gpu: 'Adreno 830', ram: '12GB', storage: '256GB/512GB/1TB', mainCamera: '200MP + 50MP + 10MP + 50MP', selfieCamera: '12MP', videoRecording: '8K@30fps, 4K@120fps', battery: '5000mAh', charging: '45W Wired', wirelessCharge: '15W Wireless', weight: '218g', dimensions: '162.8 x 77.6 x 8.2mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Ultrasonic In-Display', faceUnlock: 'Yes', colors: 'Titanium Black, Titanium Gray, Titanium Silver Blue, Titanium White Silver', os: 'Android 15, One UI 7' },
      benchmark: { antutu: 2650000, geekbenchSingle: 3100, geekbenchMulti: 10200, gamingScore: 96 }},
    { brandSlug: 'samsung', modelName: 'Galaxy S25+', slug: 'samsung-galaxy-s25-plus', releaseDate: '2025-02-01', pricePKR: 355000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: true, description: 'Large-screen flagship with powerful performance and Samsung\'s AI features.', cameraScore: 91, performanceScore: 93, batteryScore: 86, displayScore: 95, valueScore: 70, overallRating: 4.3, sortOrder: 2,
      specs: { display: '6.7" Dynamic AMOLED 2X', resolution: '3120 x 1440', refreshRate: '120Hz', protection: 'Gorilla Armor 2', chipset: 'Snapdragon 8 Elite', cpu: 'Octa-core (4x4.47GHz + 4x3.53GHz)', gpu: 'Adreno 830', ram: '12GB', storage: '256GB/512GB', mainCamera: '50MP + 12MP + 10MP', selfieCamera: '12MP', videoRecording: '8K@30fps, 4K@120fps', battery: '4900mAh', charging: '45W Wired', wirelessCharge: '15W Wireless', weight: '190g', dimensions: '158.4 x 75.8 x 8.3mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Ultrasonic In-Display', faceUnlock: 'Yes', colors: 'Icy Blue, Mint Green, Navy Blue', os: 'Android 15, One UI 7' },
      benchmark: { antutu: 2600000, geekbenchSingle: 3080, geekbenchMulti: 10000, gamingScore: 94 }},
    { brandSlug: 'samsung', modelName: 'Galaxy A56', slug: 'samsung-galaxy-a56', releaseDate: '2025-03-15', pricePKR: 115000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: true, description: 'Samsung\'s best mid-range phone with flagship-grade features at a much lower price.', cameraScore: 82, performanceScore: 78, batteryScore: 90, displayScore: 86, valueScore: 88, overallRating: 4.2, sortOrder: 3,
      specs: { display: '6.7" Super AMOLED', resolution: '2340 x 1080', refreshRate: '120Hz', protection: 'Gorilla Glass Victus+', chipset: 'Exynos 1580', cpu: 'Octa-core (4x2.9GHz + 4x2.6GHz)', gpu: 'Xclipse 530', ram: '8GB', storage: '128GB/256GB', mainCamera: '50MP + 12MP + 5MP', selfieCamera: '12MP', videoRecording: '4K@30fps', battery: '5000mAh', charging: '25W Wired', wirelessCharge: 'No', weight: '191g', dimensions: '159.4 x 74.8 x 7.8mm', network: '5G', wifi: 'WiFi 6', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'Awesome Ice Blue, Awesome Mint, Awesome Navy', os: 'Android 15, One UI 7' },
      benchmark: { antutu: 980000, geekbenchSingle: 1800, geekbenchMulti: 4500, gamingScore: 72 }},
    { brandSlug: 'samsung', modelName: 'Galaxy A36', slug: 'samsung-galaxy-a36', releaseDate: '2025-03-15', pricePKR: 85000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: true, description: 'Solid mid-range Samsung phone with great display and camera for the price.', cameraScore: 78, performanceScore: 74, batteryScore: 88, displayScore: 84, valueScore: 85, overallRating: 4.0, sortOrder: 4,
      specs: { display: '6.6" Super AMOLED', resolution: '2340 x 1080', refreshRate: '120Hz', protection: 'Gorilla Glass Victus+', chipset: 'Snapdragon 6 Gen 3', cpu: 'Octa-core (4x2.4GHz + 4x1.8GHz)', gpu: 'Adreno 710', ram: '6GB/8GB', storage: '128GB/256GB', mainCamera: '50MP + 8MP + 5MP', selfieCamera: '13MP', videoRecording: '4K@30fps', battery: '5000mAh', charging: '25W Wired', wirelessCharge: 'No', weight: '188g', dimensions: '158.2 x 74.6 x 7.7mm', network: '5G', wifi: 'WiFi 6', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'Awesome Lilac, Awesome Light Green, Awesome Black', os: 'Android 15, One UI 7' },
      benchmark: { antutu: 850000, geekbenchSingle: 1600, geekbenchMulti: 4200, gamingScore: 65 }},
    { brandSlug: 'samsung', modelName: 'Galaxy A16', slug: 'samsung-galaxy-a16', releaseDate: '2024-12-01', pricePKR: 42000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: false, description: 'Budget Samsung phone with 6 years of updates, great display, and reliable performance.', cameraScore: 68, performanceScore: 60, batteryScore: 85, displayScore: 75, valueScore: 90, overallRating: 3.8, sortOrder: 5,
      specs: { display: '6.7" Super AMOLED', resolution: '2340 x 1080', refreshRate: '90Hz', protection: 'Gorilla Glass 5', chipset: 'MediaTek Dimensity 6300', cpu: 'Octa-core (2x2.4GHz + 6x2.0GHz)', gpu: 'Mali-G57 MC2', ram: '4GB/6GB/8GB', storage: '128GB/256GB', mainCamera: '50MP + 5MP + 2MP', selfieCamera: '13MP', videoRecording: '1080p@30fps', battery: '5000mAh', charging: '25W Wired', wirelessCharge: 'No', weight: '200g', dimensions: '164.4 x 77.9 x 8.2mm', network: '5G', wifi: 'WiFi 5', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Side-Mounted', faceUnlock: 'Yes', colors: 'Black, Light Green, Blue, Gold', os: 'Android 14, One UI 6.1' },
      benchmark: { antutu: 520000, geekbenchSingle: 1200, geekbenchMulti: 3000, gamingScore: 42 }},
    { brandSlug: 'apple', modelName: 'iPhone 16 Pro Max', slug: 'iphone-16-pro-max', releaseDate: '2024-09-20', pricePKR: 575000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: true, description: 'Apple\'s most powerful iPhone with A18 Pro chip, 48MP camera system, and the largest battery ever in an iPhone.', cameraScore: 98, performanceScore: 96, batteryScore: 92, displayScore: 95, valueScore: 65, overallRating: 4.7, sortOrder: 6,
      specs: { display: '6.9" Super Retina XDR OLED', resolution: '2868 x 1320', refreshRate: '120Hz ProMotion', protection: 'Ceramic Shield', chipset: 'Apple A18 Pro', cpu: 'Hexa-core (2x4.05GHz + 4x2.42GHz)', gpu: '6-Core GPU', ram: '8GB', storage: '256GB/512GB/1TB', mainCamera: '48MP + 48MP + 12MP', selfieCamera: '12MP + 12MP 3D', videoRecording: '4K@120fps Dolby Vision', battery: '4685mAh', charging: '27W Wired', wirelessCharge: '25W MagSafe', weight: '227g', dimensions: '163 x 77.6 x 8.3mm', network: '5G Sub-6GHz', wifi: 'WiFi 7', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'No', faceUnlock: 'Face ID', colors: 'Natural Titanium, Desert Titanium, White Titanium, Black Titanium', os: 'iOS 18' },
      benchmark: { antutu: 2400000, geekbenchSingle: 3500, geekbenchMulti: 9200, gamingScore: 92 }},
    { brandSlug: 'apple', modelName: 'iPhone 16', slug: 'iphone-16', releaseDate: '2024-09-20', pricePKR: 435000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: true, description: 'The standard iPhone 16 with A18 chip, improved cameras, and Apple Intelligence features.', cameraScore: 88, performanceScore: 91, batteryScore: 82, displayScore: 86, valueScore: 68, overallRating: 4.3, sortOrder: 7,
      specs: { display: '6.1" Super Retina XDR OLED', resolution: '2556 x 1179', refreshRate: '60Hz', protection: 'Ceramic Shield', chipset: 'Apple A18', cpu: 'Hexa-core (2x4.05GHz + 4x2.42GHz)', gpu: '5-Core GPU', ram: '8GB', storage: '128GB/256GB/512GB', mainCamera: '48MP + 12MP', selfieCamera: '12MP', videoRecording: '4K@60fps Dolby Vision', battery: '3561mAh', charging: '27W Wired', wirelessCharge: '25W MagSafe', weight: '170g', dimensions: '147.6 x 71.6 x 7.8mm', network: '5G Sub-6GHz', wifi: 'WiFi 7', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'No', faceUnlock: 'Face ID', colors: 'Black, White, Blue, Teal, Pink', os: 'iOS 18' },
      benchmark: { antutu: 2100000, geekbenchSingle: 3300, geekbenchMulti: 8500, gamingScore: 85 }},
    { brandSlug: 'apple', modelName: 'iPhone 16 Plus', slug: 'iphone-16-plus', releaseDate: '2024-09-20', pricePKR: 490000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: false, description: 'Big-screen iPhone 16 Plus with A18 chip and excellent battery life for media consumption.', cameraScore: 88, performanceScore: 91, batteryScore: 90, displayScore: 86, valueScore: 65, overallRating: 4.2, sortOrder: 8,
      specs: { display: '6.7" Super Retina XDR OLED', resolution: '2778 x 1284', refreshRate: '60Hz', protection: 'Ceramic Shield', chipset: 'Apple A18', cpu: 'Hexa-core (2x4.05GHz + 4x2.42GHz)', gpu: '5-Core GPU', ram: '8GB', storage: '128GB/256GB/512GB', mainCamera: '48MP + 12MP', selfieCamera: '12MP', videoRecording: '4K@60fps Dolby Vision', battery: '4685mAh', charging: '27W Wired', wirelessCharge: '25W MagSafe', weight: '199g', dimensions: '160.9 x 77.8 x 7.8mm', network: '5G Sub-6GHz', wifi: 'WiFi 7', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'No', faceUnlock: 'Face ID', colors: 'Black, White, Blue, Teal, Pink', os: 'iOS 18' },
      benchmark: { antutu: 2100000, geekbenchSingle: 3300, geekbenchMulti: 8500, gamingScore: 85 }},
    { brandSlug: 'xiaomi', modelName: 'Xiaomi 15 Ultra', slug: 'xiaomi-15-ultra', releaseDate: '2025-03-01', pricePKR: 295000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: true, description: 'Xiaomi\'s photography flagship with Leica cameras, Snapdragon 8 Elite, and 100W charging.', cameraScore: 97, performanceScore: 95, batteryScore: 90, displayScore: 94, valueScore: 82, overallRating: 4.6, sortOrder: 9,
      specs: { display: '6.73" LTPO AMOLED', resolution: '3200 x 1440', refreshRate: '120Hz', protection: 'Xiaomi Longjing Glass', chipset: 'Snapdragon 8 Elite', cpu: 'Octa-core (4x4.47GHz + 4x3.53GHz)', gpu: 'Adreno 830', ram: '12GB/16GB', storage: '256GB/512GB/1TB', mainCamera: '50MP + 50MP + 200MP + 50MP', selfieCamera: '32MP', videoRecording: '8K@30fps, 4K@120fps', battery: '6000mAh', charging: '90W Wired', wirelessCharge: '80W Wireless', weight: '227g', dimensions: '161.4 x 75.3 x 9.4mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Ultrasonic In-Display', faceUnlock: 'Yes', colors: 'Black, White, Green', os: 'Android 15, HyperOS 2' },
      benchmark: { antutu: 2700000, geekbenchSingle: 3150, geekbenchMulti: 10500, gamingScore: 97 }},
    { brandSlug: 'xiaomi', modelName: 'Xiaomi 15', slug: 'xiaomi-15', releaseDate: '2025-02-15', pricePKR: 195000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: true, description: 'Compact flagship with Leica optics, Snapdragon 8 Elite, and premium build quality.', cameraScore: 90, performanceScore: 94, batteryScore: 82, displayScore: 92, valueScore: 85, overallRating: 4.4, sortOrder: 10,
      specs: { display: '6.36" LTPO AMOLED', resolution: '2640 x 1200', refreshRate: '120Hz', protection: 'Xiaomi Longjing Glass', chipset: 'Snapdragon 8 Elite', cpu: 'Octa-core (4x4.47GHz + 4x3.53GHz)', gpu: 'Adreno 830', ram: '12GB', storage: '256GB/512GB', mainCamera: '50MP + 50MP + 50MP', selfieCamera: '32MP', videoRecording: '8K@30fps, 4K@120fps', battery: '5400mAh', charging: '90W Wired', wirelessCharge: '50W Wireless', weight: '191g', dimensions: '152.1 x 71.2 x 8.1mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Ultrasonic In-Display', faceUnlock: 'Yes', colors: 'Black, White, Silver', os: 'Android 15, HyperOS 2' },
      benchmark: { antutu: 2650000, geekbenchSingle: 3100, geekbenchMulti: 10200, gamingScore: 95 }},
    { brandSlug: 'xiaomi', modelName: 'Redmi Note 14 Pro+', slug: 'xiaomi-redmi-note-14-pro-plus', releaseDate: '2025-01-15', pricePKR: 78000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: true, description: 'Best upper mid-range phone in Pakistan with 200MP camera, 120W charging, and IP68 rating.', cameraScore: 84, performanceScore: 76, batteryScore: 86, displayScore: 83, valueScore: 92, overallRating: 4.3, sortOrder: 11,
      specs: { display: '6.67" AMOLED', resolution: '2712 x 1220', refreshRate: '120Hz', protection: 'Corning Gorilla Glass Victus', chipset: 'MediaTek Dimensity 7350 Pro', cpu: 'Octa-core (2x2.8GHz + 6x2.3GHz)', gpu: 'Mali-G615 MC4', ram: '8GB/12GB', storage: '256GB/512GB', mainCamera: '200MP + 8MP + 2MP', selfieCamera: '20MP', videoRecording: '4K@30fps', battery: '6200mAh', charging: '120W Wired', wirelessCharge: 'No', weight: '205g', dimensions: '162.3 x 75.3 x 8.5mm', network: '5G', wifi: 'WiFi 6', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'Purple, Green, Black, White', os: 'Android 14, HyperOS 2' },
      benchmark: { antutu: 920000, geekbenchSingle: 1700, geekbenchMulti: 4400, gamingScore: 68 }},
    { brandSlug: 'xiaomi', modelName: 'Redmi Note 14', slug: 'xiaomi-redmi-note-14', releaseDate: '2025-01-10', pricePKR: 48000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: false, description: 'Incredible value for money phone with 108MP camera, 5G, and 45W charging under 50K.', cameraScore: 74, performanceScore: 68, batteryScore: 88, displayScore: 76, valueScore: 95, overallRating: 4.1, sortOrder: 12,
      specs: { display: '6.67" AMOLED', resolution: '2400 x 1080', refreshRate: '120Hz', protection: 'Corning Gorilla Glass 3', chipset: 'MediaTek Dimensity 7025 Ultra', cpu: 'Octa-core (2x2.5GHz + 6x2.0GHz)', gpu: 'Mali-G610 MC3', ram: '6GB/8GB', storage: '128GB/256GB', mainCamera: '108MP + 8MP', selfieCamera: '20MP', videoRecording: '1080p@60fps', battery: '5110mAh', charging: '45W Wired', wirelessCharge: 'No', weight: '190g', dimensions: '162.3 x 75.4 x 7.9mm', network: '5G', wifi: 'WiFi 5', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Side-Mounted', faceUnlock: 'Yes', colors: 'Black, Green, Purple', os: 'Android 14, HyperOS 2' },
      benchmark: { antutu: 650000, geekbenchSingle: 1300, geekbenchMulti: 3500, gamingScore: 48 }},
    { brandSlug: 'oneplus', modelName: 'OnePlus 13', slug: 'oneplus-13', releaseDate: '2025-01-07', pricePKR: 265000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: true, description: 'OnePlus flagship with Snapdragon 8 Elite, 6000mAh battery, and 100W SUPERVOOC charging.', cameraScore: 88, performanceScore: 95, batteryScore: 94, displayScore: 93, valueScore: 80, overallRating: 4.5, sortOrder: 13,
      specs: { display: '6.82" LTPO AMOLED', resolution: '3168 x 1440', refreshRate: '120Hz', protection: 'Xiaomi Longjing Glass', chipset: 'Snapdragon 8 Elite', cpu: 'Octa-core (4x4.47GHz + 4x3.53GHz)', gpu: 'Adreno 830', ram: '12GB/16GB', storage: '256GB/512GB', mainCamera: '50MP + 50MP + 50MP', selfieCamera: '32MP', videoRecording: '8K@30fps, 4K@120fps', battery: '6000mAh', charging: '100W Wired', wirelessCharge: '50W Wireless', weight: '213g', dimensions: '162.9 x 76.5 x 8.5mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Ultrasonic In-Display', faceUnlock: 'Yes', colors: 'Black, White, Green', os: 'Android 15, OxygenOS 15' },
      benchmark: { antutu: 2680000, geekbenchSingle: 3120, geekbenchMulti: 10300, gamingScore: 96 }},
    { brandSlug: 'oneplus', modelName: 'OnePlus 13R', slug: 'oneplus-13r', releaseDate: '2025-01-07', pricePKR: 145000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: true, description: 'Flagship killer with Snapdragon 8 Gen 3, 6000mAh battery, and premium design at a lower price.', cameraScore: 80, performanceScore: 88, batteryScore: 92, displayScore: 87, valueScore: 86, overallRating: 4.3, sortOrder: 14,
      specs: { display: '6.78" LTPO AMOLED', resolution: '2780 x 1264', refreshRate: '120Hz', protection: 'Corning Gorilla Glass Victus 2', chipset: 'Snapdragon 8 Gen 3', cpu: 'Octa-core (1x3.3GHz + 3x3.2GHz + 2x3.0GHz + 2x2.3GHz)', gpu: 'Adreno 750', ram: '8GB/12GB/16GB', storage: '128GB/256GB/512GB', mainCamera: '50MP + 8MP + 50MP', selfieCamera: '16MP', videoRecording: '4K@60fps', battery: '6000mAh', charging: '80W Wired', wirelessCharge: '50W Wireless', weight: '198g', dimensions: '161.7 x 75.8 x 8.5mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'Astral Trail, Luminous Frost, Nebula Green', os: 'Android 15, OxygenOS 15' },
      benchmark: { antutu: 2200000, geekbenchSingle: 2800, geekbenchMulti: 8000, gamingScore: 88 }},
    { brandSlug: 'realme', modelName: 'Realme GT 7 Pro', slug: 'realme-gt-7-pro', releaseDate: '2025-02-20', pricePKR: 175000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: true, description: 'Gaming-focused flagship with Snapdragon 8 Elite, 6500mAh battery, and 120W charging.', cameraScore: 82, performanceScore: 95, batteryScore: 95, displayScore: 91, valueScore: 88, overallRating: 4.4, sortOrder: 15,
      specs: { display: '6.78" LTPO AMOLED', resolution: '2780 x 1264', refreshRate: '120Hz', protection: 'Schott Xensation Up', chipset: 'Snapdragon 8 Elite', cpu: 'Octa-core (4x4.47GHz + 4x3.53GHz)', gpu: 'Adreno 830', ram: '12GB/16GB', storage: '256GB/512GB', mainCamera: '50MP + 50MP + 8MP', selfieCamera: '16MP', videoRecording: '4K@120fps', battery: '6500mAh', charging: '120W Wired', wirelessCharge: 'No', weight: '222g', dimensions: '162.4 x 76.2 x 8.6mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Ultrasonic In-Display', faceUnlock: 'Yes', colors: 'Saturn Brown, Mars Orange, Galaxy White', os: 'Android 15, Realme UI 6.0' },
      benchmark: { antutu: 2700000, geekbenchSingle: 3150, geekbenchMulti: 10500, gamingScore: 98 }},
    { brandSlug: 'realme', modelName: 'Realme 14 Pro+', slug: 'realme-14-pro-plus', releaseDate: '2025-03-01', pricePKR: 95000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: true, description: 'Mid-range camera king with 50MP Sony IMX906, 3D curved display, and premium design.', cameraScore: 85, performanceScore: 78, batteryScore: 85, displayScore: 86, valueScore: 88, overallRating: 4.2, sortOrder: 16,
      specs: { display: '6.78" Curved AMOLED', resolution: '2780 x 1264', refreshRate: '120Hz', protection: 'Schott Xensation', chipset: 'Snapdragon 7 Gen 3', cpu: 'Octa-core (1x2.63GHz + 3x2.4GHz + 4x1.8GHz)', gpu: 'Adreno 720', ram: '8GB/12GB', storage: '256GB/512GB', mainCamera: '50MP + 50MP + 8MP', selfieCamera: '50MP', videoRecording: '4K@60fps', battery: '5800mAh', charging: '80W Wired', wirelessCharge: 'No', weight: '192g', dimensions: '161.7 x 75.0 x 8.2mm', network: '5G', wifi: 'WiFi 6', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'Luminous Blue, Pearl White, Green', os: 'Android 15, Realme UI 6.0' },
      benchmark: { antutu: 900000, geekbenchSingle: 1700, geekbenchMulti: 4300, gamingScore: 66 }},
    { brandSlug: 'realme', modelName: 'Realme C75', slug: 'realme-c75', releaseDate: '2025-02-01', pricePKR: 35000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: false, description: 'Best phone under 40K with 6000mAh battery, 45W charging, and IP69 rating.', cameraScore: 60, performanceScore: 52, batteryScore: 92, displayScore: 65, valueScore: 96, overallRating: 3.6, sortOrder: 17,
      specs: { display: '6.72" IPS LCD', resolution: '2400 x 1080', refreshRate: '90Hz', protection: 'Panda Glass', chipset: 'Unisoc T612', cpu: 'Octa-core (1.8GHz)', gpu: 'Mali-G57', ram: '6GB/8GB', storage: '128GB/256GB', mainCamera: '50MP + 2MP', selfieCamera: '8MP', videoRecording: '1080p@30fps', battery: '6000mAh', charging: '45W Wired', wirelessCharge: 'No', weight: '200g', dimensions: '168.3 x 76.3 x 8.3mm', network: '4G LTE', wifi: 'WiFi 5', bluetooth: '5.0', nfc: 'No', usb: 'USB Type-C 2.0', fingerprint: 'Side-Mounted', faceUnlock: 'Yes', colors: 'Black, Green, Gold', os: 'Android 14, Realme UI 5.0' },
      benchmark: { antutu: 280000, geekbenchSingle: 800, geekbenchMulti: 2000, gamingScore: 25 }},
    { brandSlug: 'vivo', modelName: 'Vivo X200 Pro', slug: 'vivo-x200-pro', releaseDate: '2025-01-15', pricePKR: 235000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: false, description: 'Photography powerhouse with ZEISS optics, 200MP periscope, and Dimensity 9400.', cameraScore: 96, performanceScore: 91, batteryScore: 86, displayScore: 90, valueScore: 76, overallRating: 4.4, sortOrder: 18,
      specs: { display: '6.78" LTPO AMOLED', resolution: '2800 x 1260', refreshRate: '120Hz', protection: 'Schott Xensation Alpha', chipset: 'MediaTek Dimensity 9400', cpu: 'Octa-core (1x3.63GHz + 3x3.3GHz + 4x2.4GHz)', gpu: 'Immortalis-G925', ram: '12GB/16GB', storage: '256GB/512GB', mainCamera: '50MP + 50MP + 200MP', selfieCamera: '50MP', videoRecording: '8K@30fps, 4K@120fps', battery: '6000mAh', charging: '100W Wired', wirelessCharge: '30W Wireless', weight: '228g', dimensions: '162.4 x 75.9 x 8.7mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'Black, Blue, White', os: 'Android 15, FuntouchOS 15' },
      benchmark: { antutu: 2500000, geekbenchSingle: 2900, geekbenchMulti: 9500, gamingScore: 90 }},
    { brandSlug: 'vivo', modelName: 'Vivo V40', slug: 'vivo-v40', releaseDate: '2024-09-01', pricePKR: 82000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: false, description: 'Stylish mid-ranger with ZEISS camera, slim design, and fast 80W charging.', cameraScore: 80, performanceScore: 70, batteryScore: 80, displayScore: 80, valueScore: 82, overallRating: 3.9, sortOrder: 19,
      specs: { display: '6.78" AMOLED', resolution: '2800 x 1260', refreshRate: '120Hz', protection: 'Schott Xensation', chipset: 'Snapdragon 7 Gen 3', cpu: 'Octa-core (1x2.63GHz + 3x2.4GHz + 4x1.8GHz)', gpu: 'Adreno 720', ram: '8GB', storage: '256GB', mainCamera: '50MP + 50MP', selfieCamera: '50MP', videoRecording: '4K@30fps', battery: '5500mAh', charging: '80W Wired', wirelessCharge: 'No', weight: '183g', dimensions: '164.2 x 75.1 x 7.5mm', network: '5G', wifi: 'WiFi 6', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'Black, Blue, Purple', os: 'Android 14, FuntouchOS 14' },
      benchmark: { antutu: 880000, geekbenchSingle: 1650, geekbenchMulti: 4200, gamingScore: 62 }},
    { brandSlug: 'oppo', modelName: 'Oppo Find X8 Pro', slug: 'oppo-find-x8-pro', releaseDate: '2025-01-20', pricePKR: 255000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: false, description: 'Premium flagship with Hasselblad cameras, Snapdragon 8 Elite, and elegant design.', cameraScore: 94, performanceScore: 94, batteryScore: 88, displayScore: 92, valueScore: 74, overallRating: 4.4, sortOrder: 20,
      specs: { display: '6.78" LTPO AMOLED', resolution: '2780 x 1264', refreshRate: '120Hz', protection: 'Xiaomi Longjing Glass', chipset: 'Snapdragon 8 Elite', cpu: 'Octa-core (4x4.47GHz + 4x3.53GHz)', gpu: 'Adreno 830', ram: '12GB/16GB', storage: '256GB/512GB', mainCamera: '50MP + 50MP + 50MP + 50MP', selfieCamera: '32MP', videoRecording: '4K@120fps', battery: '5910mAh', charging: '80W Wired', wirelessCharge: '50W Wireless', weight: '215g', dimensions: '162.3 x 76.3 x 8.2mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Ultrasonic In-Display', faceUnlock: 'Yes', colors: 'Black, White, Blue', os: 'Android 15, ColorOS 15' },
      benchmark: { antutu: 2670000, geekbenchSingle: 3100, geekbenchMulti: 10200, gamingScore: 95 }},
    { brandSlug: 'oppo', modelName: 'Oppo Reno 13 Pro', slug: 'oppo-reno-13-pro', releaseDate: '2025-02-10', pricePKR: 105000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: false, description: 'Sleek mid-range phone with great cameras, AI features, and fast 80W charging.', cameraScore: 83, performanceScore: 78, batteryScore: 82, displayScore: 84, valueScore: 82, overallRating: 4.1, sortOrder: 21,
      specs: { display: '6.7" AMOLED', resolution: '2412 x 1080', refreshRate: '120Hz', protection: 'Gorilla Glass Victus 2', chipset: 'MediaTek Dimensity 8350', cpu: 'Octa-core (2x3.35GHz + 6x2.2GHz)', gpu: 'Mali-G615 MC6', ram: '8GB/12GB', storage: '256GB/512GB', mainCamera: '50MP + 8MP + 50MP', selfieCamera: '50MP', videoRecording: '4K@60fps', battery: '5800mAh', charging: '80W Wired', wirelessCharge: 'No', weight: '190g', dimensions: '161.9 x 74.7 x 8.1mm', network: '5G', wifi: 'WiFi 6', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'Black, Silver, Pink', os: 'Android 15, ColorOS 15' },
      benchmark: { antutu: 950000, geekbenchSingle: 1800, geekbenchMulti: 4600, gamingScore: 70 }},
    { brandSlug: 'google', modelName: 'Pixel 9 Pro XL', slug: 'google-pixel-9-pro-xl', releaseDate: '2024-08-22', pricePKR: 310000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: false, description: 'Google\'s best phone with incredible AI, top cameras, 7 years of updates, and pure Android.', cameraScore: 97, performanceScore: 88, batteryScore: 88, displayScore: 90, valueScore: 72, overallRating: 4.5, sortOrder: 22,
      specs: { display: '6.8" LTPO OLED', resolution: '2892 x 1344', refreshRate: '120Hz', protection: 'Gorilla Glass Victus 2', chipset: 'Google Tensor G4', cpu: 'Octa-core (1x3.1GHz + 3x2.6GHz + 4x1.92GHz)', gpu: 'Mali-G715 MC7', ram: '16GB', storage: '128GB/256GB/512GB', mainCamera: '50MP + 48MP + 48MP', selfieCamera: '42MP', videoRecording: '4K@60fps', battery: '4700mAh', charging: '37W Wired', wirelessCharge: '23W Wireless', weight: '221g', dimensions: '162.8 x 76.6 x 8.5mm', network: '5G Sub-6GHz', wifi: 'WiFi 7', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'Obsidian, Porcelain, Hazel, Rose Quartz', os: 'Android 15, Pixel UI' },
      benchmark: { antutu: 1800000, geekbenchSingle: 2800, geekbenchMulti: 7800, gamingScore: 78 }},
    { brandSlug: 'google', modelName: 'Pixel 9a', slug: 'google-pixel-9a', releaseDate: '2025-03-19', pricePKR: 95000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: true, description: 'Best mid-range camera phone with Tensor G4, 7 years of updates, and premium build.', cameraScore: 88, performanceScore: 76, batteryScore: 84, displayScore: 80, valueScore: 90, overallRating: 4.2, sortOrder: 23,
      specs: { display: '6.3" OLED', resolution: '2400 x 1080', refreshRate: '120Hz', protection: 'Gorilla Glass 3', chipset: 'Google Tensor G4', cpu: 'Octa-core (1x3.1GHz + 3x2.6GHz + 4x1.92GHz)', gpu: 'Mali-G715 MC7', ram: '8GB', storage: '128GB/256GB', mainCamera: '48MP + 13MP', selfieCamera: '13MP', videoRecording: '4K@60fps', battery: '5000mAh', charging: '23W Wired', wirelessCharge: 'No', weight: '186g', dimensions: '154.7 x 73.4 x 8.7mm', network: '5G Sub-6GHz', wifi: 'WiFi 6E', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Rear-Mounted', faceUnlock: 'Yes', colors: 'Obsidian, Iris, Aloe', os: 'Android 15, Pixel UI' },
      benchmark: { antutu: 1750000, geekbenchSingle: 2700, geekbenchMulti: 7600, gamingScore: 75 }},
    { brandSlug: 'motorola', modelName: 'Motorola Edge 60 Pro', slug: 'motorola-edge-60-pro', releaseDate: '2025-03-01', pricePKR: 185000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: true, description: 'Premium Motorola phone with clean Android, 125W turbo charging, and S Pen support.', cameraScore: 84, performanceScore: 90, batteryScore: 88, displayScore: 89, valueScore: 84, overallRating: 4.2, sortOrder: 24,
      specs: { display: '6.8" pOLED', resolution: '2712 x 1220', refreshRate: '165Hz', protection: 'Gorilla Glass Victus', chipset: 'Snapdragon 8 Elite', cpu: 'Octa-core (4x4.47GHz + 4x3.53GHz)', gpu: 'Adreno 830', ram: '12GB/16GB', storage: '256GB/512GB', mainCamera: '50MP + 50MP + 64MP', selfieCamera: '50MP', videoRecording: '8K@30fps, 4K@120fps', battery: '6000mAh', charging: '125W Wired', wirelessCharge: '50W Wireless', weight: '198g', dimensions: '162.5 x 76.0 x 8.3mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Ultrasonic In-Display', faceUnlock: 'Yes', colors: 'Black, Blue, Gray', os: 'Android 15, MyUX' },
      benchmark: { antutu: 2660000, geekbenchSingle: 3100, geekbenchMulti: 10100, gamingScore: 95 }},
    { brandSlug: 'infinix', modelName: 'Infinix Note 40 Pro', slug: 'infinix-note-40-pro', releaseDate: '2024-10-01', pricePKR: 52000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: false, description: 'Best budget phone with 108MP camera, wireless charging, and premium design under 55K.', cameraScore: 72, performanceScore: 62, batteryScore: 86, displayScore: 74, valueScore: 94, overallRating: 3.9, sortOrder: 25,
      specs: { display: '6.78" AMOLED', resolution: '2436 x 1080', refreshRate: '120Hz', protection: 'Corning Gorilla Glass 5', chipset: 'MediaTek Helio G100', cpu: 'Octa-core (2x2.2GHz + 6x1.8GHz)', gpu: 'Mali-G57 MC2', ram: '8GB', storage: '256GB', mainCamera: '108MP + 2MP + 2MP', selfieCamera: '32MP', videoRecording: '1440p@30fps', battery: '5000mAh', charging: '68W Wired', wirelessCharge: '20W Wireless', weight: '194g', dimensions: '164.3 x 74.6 x 7.9mm', network: '4G LTE', wifi: 'WiFi 5', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Side-Mounted', faceUnlock: 'Yes', colors: 'Titan Gold, Obsidian Black, Vintage Green', os: 'Android 14, XOS 14' },
      benchmark: { antutu: 450000, geekbenchSingle: 900, geekbenchMulti: 2500, gamingScore: 35 }},
    { brandSlug: 'tecno', modelName: 'Tecno Camon 30 Premier', slug: 'tecno-camon-30-premier', releaseDate: '2024-09-15', pricePKR: 72000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: false, description: 'Camera champion in budget segment with Sony IMX890 sensor and AI photography features.', cameraScore: 82, performanceScore: 66, batteryScore: 82, displayScore: 78, valueScore: 88, overallRating: 4.0, sortOrder: 26,
      specs: { display: '6.78" LTPO AMOLED', resolution: '2800 x 1260', refreshRate: '120Hz', protection: 'Corning Gorilla Glass 5', chipset: 'MediaTek Dimensity 8200', cpu: 'Octa-core (1x3.1GHz + 3x3.0GHz + 4x2.0GHz)', gpu: 'Mali-G610 MC6', ram: '8GB/12GB', storage: '256GB/512GB', mainCamera: '50MP + 50MP + 12MP', selfieCamera: '50MP', videoRecording: '4K@30fps', battery: '5000mAh', charging: '70W Wired', wirelessCharge: 'No', weight: '195g', dimensions: '163.7 x 75.4 x 8.2mm', network: '5G', wifi: 'WiFi 6', bluetooth: '5.3', nfc: 'Yes', usb: 'USB Type-C 2.0', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'Black, Brown', os: 'Android 14, HiOS 14' },
      benchmark: { antutu: 900000, geekbenchSingle: 1600, geekbenchMulti: 4000, gamingScore: 58 }},
    { brandSlug: 'infinix', modelName: 'Infinix Smart 9', slug: 'infinix-smart-9', releaseDate: '2025-01-15', pricePKR: 22000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: false, description: 'Ultra-budget phone with 90Hz display, 5000mAh battery, and Android 14 Go under 25K.', cameraScore: 48, performanceScore: 40, batteryScore: 85, displayScore: 55, valueScore: 95, overallRating: 3.3, sortOrder: 27,
      specs: { display: '6.7" IPS LCD', resolution: '1612 x 720', refreshRate: '90Hz', protection: 'Tempered Glass', chipset: 'Unisoc T606', cpu: 'Octa-core (1.6GHz)', gpu: 'Mali-G57 MP1', ram: '3GB/4GB', storage: '64GB/128GB', mainCamera: '13MP + 2MP', selfieCamera: '8MP', videoRecording: '1080p@30fps', battery: '5000mAh', charging: '10W Wired', wirelessCharge: 'No', weight: '190g', dimensions: '165.7 x 76.0 x 8.5mm', network: '4G LTE', wifi: 'WiFi 5', bluetooth: '5.0', nfc: 'No', usb: 'USB Type-C', fingerprint: 'Rear-Mounted', faceUnlock: 'Yes', colors: 'Black, Blue, Green', os: 'Android 14 Go Edition, XOS 14' },
      benchmark: { antutu: 180000, geekbenchSingle: 600, geekbenchMulti: 1500, gamingScore: 15 }},
    { brandSlug: 'tecno', modelName: 'Tecno Spark 30', slug: 'tecno-spark-30', releaseDate: '2025-01-01', pricePKR: 18000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: false, trending: false, description: 'Cheapest entry-level smartphone with 90Hz screen, 5000mAh battery, and 13MP camera.', cameraScore: 42, performanceScore: 38, batteryScore: 84, displayScore: 50, valueScore: 96, overallRating: 3.2, sortOrder: 28,
      specs: { display: '6.6" IPS LCD', resolution: '1612 x 720', refreshRate: '90Hz', protection: 'Tempered Glass', chipset: 'Unisoc T606', cpu: 'Octa-core (1.6GHz)', gpu: 'Mali-G57 MP1', ram: '3GB/4GB', storage: '64GB/128GB', mainCamera: '13MP + 2MP', selfieCamera: '8MP', videoRecording: '1080p@30fps', battery: '5000mAh', charging: '10W Wired', wirelessCharge: 'No', weight: '195g', dimensions: '164.5 x 75.8 x 8.7mm', network: '4G LTE', wifi: 'WiFi 5', bluetooth: '5.0', nfc: 'No', usb: 'USB Type-C', fingerprint: 'Rear-Mounted', faceUnlock: 'Yes', colors: 'Black, Blue, White', os: 'Android 14 Go, HiOS 14' },
      benchmark: { antutu: 170000, geekbenchSingle: 550, geekbenchMulti: 1400, gamingScore: 12 }},
    { brandSlug: 'nothing', modelName: 'Nothing Phone 3', slug: 'nothing-phone-3', releaseDate: '2025-03-01', pricePKR: 155000, ptaStatus: 'PTA Approved', ptaApproved: true, featured: true, trending: true, description: 'Unique transparent design with Glyph LED interface, Snapdragon 8 Elite, and clean Android.', cameraScore: 82, performanceScore: 93, batteryScore: 85, displayScore: 88, valueScore: 82, overallRating: 4.3, sortOrder: 29,
      specs: { display: '6.7" LTPO OLED', resolution: '2812 x 1260', refreshRate: '120Hz', protection: 'Gorilla Glass Victus 2', chipset: 'Snapdragon 8 Elite', cpu: 'Octa-core (4x4.47GHz + 4x3.53GHz)', gpu: 'Adreno 830', ram: '12GB', storage: '256GB/512GB', mainCamera: '50MP + 50MP + 50MP', selfieCamera: '50MP', videoRecording: '4K@120fps', battery: '5500mAh', charging: '60W Wired', wirelessCharge: '15W Wireless', weight: '196g', dimensions: '162.1 x 77.3 x 8.2mm', network: '5G SA/NSA', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Optical In-Display', faceUnlock: 'Yes', colors: 'White, Black, Gray', os: 'Android 15, Nothing OS 3.0' },
      benchmark: { antutu: 2640000, geekbenchSingle: 3080, geekbenchMulti: 10100, gamingScore: 94 }},
    // Upcoming
    { brandSlug: 'samsung', modelName: 'Galaxy Z Fold 7', slug: 'samsung-galaxy-z-fold-7', releaseDate: '2025-08-15', pricePKR: 580000, ptaStatus: 'Not Available', ptaApproved: false, featured: false, trending: false, upcoming: true, description: 'Samsung\'s next-gen foldable phone with improved durability and S Pen support.', sortOrder: 30,
      specs: { display: '7.6" Foldable Dynamic AMOLED 2X', resolution: '2160 x 1856', refreshRate: '120Hz', protection: 'Gorilla Armor 2', chipset: 'Snapdragon 8 Elite (Expected)', cpu: 'TBA', gpu: 'TBA', ram: '12GB (Expected)', storage: '256GB/512GB/1TB', mainCamera: 'TBA', selfieCamera: 'TBA', videoRecording: 'TBA', battery: 'TBA', charging: 'TBA', wirelessCharge: 'TBA', weight: 'TBA', dimensions: 'TBA', network: '5G', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Side-Mounted', faceUnlock: 'Yes', colors: 'TBA', os: 'Android 15, One UI 7 (Expected)' }},
    { brandSlug: 'apple', modelName: 'iPhone 17 Pro Max', slug: 'iphone-17-pro-max', releaseDate: '2025-09-20', pricePKR: 650000, ptaStatus: 'Not Available', ptaApproved: false, featured: false, trending: false, upcoming: true, description: 'Apple\'s next-gen iPhone with A19 Pro chip, 48MP ultra-wide, and all-new design.', sortOrder: 31,
      specs: { display: '6.9" ProMotion OLED (Expected)', resolution: 'TBA', refreshRate: '120Hz', protection: 'Ceramic Shield 2', chipset: 'Apple A19 Pro (Expected)', cpu: 'TBA', gpu: 'TBA', ram: 'TBA', storage: '256GB/512GB/1TB', mainCamera: 'TBA', selfieCamera: 'TBA', videoRecording: 'TBA', battery: 'TBA', charging: 'TBA', wirelessCharge: 'TBA', weight: 'TBA', dimensions: 'TBA', network: '5G', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C', fingerprint: 'No', faceUnlock: 'Face ID', colors: 'TBA', os: 'iOS 19 (Expected)' }},
    { brandSlug: 'xiaomi', modelName: 'Xiaomi 16', slug: 'xiaomi-16', releaseDate: '2025-10-01', pricePKR: 210000, ptaStatus: 'Not Available', ptaApproved: false, featured: false, trending: false, upcoming: true, description: 'Next-gen Xiaomi compact flagship with Snapdragon 8 Gen 5 and Leica optics.', sortOrder: 32,
      specs: { display: '6.36" LTPO AMOLED (Expected)', resolution: 'TBA', refreshRate: '120Hz', protection: 'TBA', chipset: 'Snapdragon 8 Gen 5 (Expected)', cpu: 'TBA', gpu: 'TBA', ram: '12GB/16GB', storage: '256GB/512GB/1TB', mainCamera: 'TBA', selfieCamera: 'TBA', videoRecording: 'TBA', battery: 'TBA', charging: 'TBA', wirelessCharge: 'TBA', weight: 'TBA', dimensions: 'TBA', network: '5G', wifi: 'WiFi 7', bluetooth: '5.4', nfc: 'Yes', usb: 'USB Type-C 3.2', fingerprint: 'Ultrasonic In-Display', faceUnlock: 'Yes', colors: 'TBA', os: 'Android 16, HyperOS 3 (Expected)' }},
  ];

  for (const p of phoneData) {
    const brandId = await getBrandId(p.brandSlug);
    const { brandSlug, specs: specData, benchmark: benchData, ...phoneFields } = p;
    await db.phone.upsert({
      where: { slug: p.slug },
      update: { ...phoneFields, brandId },
      create: { ...phoneFields, brandId },
    });
    if (specData) {
      await db.phoneSpecs.upsert({
        where: { phoneId: (await db.phone.findUnique({ where: { slug: p.slug } }))!.id },
        update: { ...specData },
        create: { phoneId: (await db.phone.findUnique({ where: { slug: p.slug } }))!.id, ...specData },
      });
    }
    if (benchData) {
      await db.phoneBenchmark.upsert({
        where: { phoneId: (await db.phone.findUnique({ where: { slug: p.slug } }))!.id },
        update: benchData,
        create: { phoneId: (await db.phone.findUnique({ where: { slug: p.slug } }))!.id, ...benchData },
      });
    }
  }
  console.log(`✅ ${phoneData.length} phones created`);

  // News
  const newsData = [
    { title: 'Samsung Galaxy S25 Ultra: The Complete Review for Pakistani Buyers', slug: 'samsung-galaxy-s25-ultra-review', content: 'The Samsung Galaxy S25 Ultra has finally arrived in Pakistan, and it is nothing short of extraordinary. Priced at PKR 425,000, this flagship device brings a host of improvements over its predecessor. The Snapdragon 8 Elite chipset delivers unmatched performance, while the 200MP main camera continues to set new standards in mobile photography. Pakistani buyers will appreciate the PTA-approved status, making it fully functional on local networks without any SIM lock issues. The titanium build feels premium, the 6.9-inch Dynamic AMOLED 2X display is stunning, and the S Pen remains one of the most useful smartphone accessories available. If you are looking for the best Android phone money can buy in Pakistan right now, this is it.', excerpt: 'Complete review of Samsung Galaxy S25 Ultra for Pakistani buyers', category: 'Reviews', image: '', author: 'PhoneDock Team', published: true, featured: true },
    { title: 'Best Smartphones Under 50,000 PKR in Pakistan (2025)', slug: 'best-phones-under-50k-pakistan-2025', content: 'Finding a great smartphone under 50,000 PKR in Pakistan is easier than ever in 2025. The Xiaomi Redmi Note 14 at PKR 48,000 offers incredible value with its 108MP camera, 5G connectivity, and 120Hz AMOLED display. The Samsung Galaxy A16 at PKR 42,000 brings Samsung reliability with 6 years of software updates, Super AMOLED display, and 5G support. For budget-conscious buyers, the Infinix Note 40 Pro at PKR 52,000 (slightly above budget) and the Realme C75 at PKR 35,000 offer compelling alternatives. All these phones are PTA-approved and readily available across Pakistan.', excerpt: 'Top picks for best budget phones in Pakistan under 50K PKR', category: 'Buyer Guide', image: '', author: 'PhoneDock Team', published: true, featured: true },
    { title: 'iPhone 16 Pro Max vs Samsung Galaxy S25 Ultra: Which to Buy?', slug: 'iphone-16-pro-max-vs-samsung-s25-ultra', content: 'The battle between Apple and Samsung flagship phones continues in 2025. The iPhone 16 Pro Max at PKR 575,000 and the Samsung Galaxy S25 Ultra at PKR 425,000 represent the very best from both ecosystems. The iPhone excels in video recording, app ecosystem, and long-term software support, while the Samsung offers a more versatile camera system, S Pen functionality, and better value for money. For Pakistani users, the Samsung is PTA-approved and easier to import, while the iPhone commands a significant price premium. We break down every aspect to help you make the right choice for your needs and budget.', excerpt: 'Detailed comparison between Apple and Samsung flagships for Pakistan', category: 'Comparisons', image: '', author: 'PhoneDock Team', published: true, featured: false },
    { title: 'PTA Tax Guide 2025: Complete Mobile Phone Import Rules for Pakistan', slug: 'pta-tax-guide-2025-pakistan', content: 'Understanding PTA (Pakistan Telecommunication Authority) regulations is crucial for anyone buying or importing a smartphone in Pakistan. In 2025, the PTA DIRBS system continues to require all mobile devices to be registered before they can be used on local networks. For passports, the tax ranges from PKR 350 to PKR 93,000 depending on the phone value. For CNIC registration, taxes are higher. Non-PTA approved phones face blocking after a grace period. This comprehensive guide covers everything you need to know about PTA registration, tax calculations, and the consequences of using unregistered phones in Pakistan.', excerpt: 'Everything you need to know about PTA mobile registration in 2025', category: 'Guides', image: '', author: 'PhoneDock Team', published: true, featured: false },
    { title: 'Nothing Phone 3 Launches in Pakistan: Price, Specs, and Availability', slug: 'nothing-phone-3-pakistan-launch', content: 'Nothing has officially launched the Phone 3 in Pakistan at PKR 155,000. The phone features the Snapdragon 8 Elite chipset, a unique transparent design with the Glyph LED interface, and clean Android 15 with Nothing OS 3.0. Pakistani buyers can purchase it through authorized retailers in major cities including Karachi, Lahore, and Islamabad. The phone is PTA-approved and available in White, Black, and Gray color options. Pre-orders have already started, and the first batch is expected to sell out quickly due to the strong brand following in Pakistan.', excerpt: 'Nothing Phone 3 is now available in Pakistan', category: 'News', image: '', author: 'PhoneDock Team', published: true, featured: false },
  ];

  for (const n of newsData) {
    await db.news.upsert({ where: { slug: n.slug }, update: n, create: n });
  }
  console.log(`✅ ${newsData.length} news articles created`);

  // Sponsors
  const sponsorData = [
    { name: 'Daraz Mobile Week', image: '', url: 'https://daraz.pk', position: 'homepage_banner', active: true },
    { name: 'Samsung Pakistan', image: '', url: 'https://samsung.com/pk', position: 'brand_banner', active: true },
    { name: 'Amazon Deals', image: '', url: 'https://amazon.com', position: 'sidebar', active: true },
  ];

  for (const s of sponsorData) {
    await db.sponsor.upsert({ where: { id: s.name.replace(/\s/g, '-').toLowerCase() }, update: s, create: { ...s, id: s.name.replace(/\s/g, '-').toLowerCase() } });
  }
  console.log(`✅ ${sponsorData.length} sponsors created`);

  // Admin user
  const adminPassword = await hash('admin123', 12);
  await db.admin.upsert({
    where: { email: 'admin@phonedock.pk' },
    update: {},
    create: { email: 'admin@phonedock.pk', password: adminPassword, name: 'PhoneDock Admin', role: 'super_admin' },
  });
  console.log('✅ Admin user created (admin@phonedock.pk / admin123)');

  // Reviews
  const reviews = [
    { phoneSlug: 'samsung-galaxy-s25-ultra', rating: 4.5, pros: 'Incredible camera system, S Pen is very useful, premium titanium build, excellent display', cons: 'Expensive, charging could be faster at 45W, thick bezels compared to Chinese competitors', content: 'The Galaxy S25 Ultra is Samsung at its absolute best. The 200MP camera takes stunning photos in all conditions, and the AI features like Circle to Search and Live Translate are genuinely useful for Pakistani users. The S Pen is perfect for quick notes and signing documents. Battery life easily lasts a full day of heavy use. At PKR 425,000, it is a significant investment, but you get the most complete smartphone package available.', author: 'PhoneDock Team', published: true },
    { phoneSlug: 'iphone-16-pro-max', rating: 4.7, pros: 'Best video recording, amazing app ecosystem, 7 years of updates, excellent build quality', cons: 'Very expensive, slow charging, no fingerprint sensor, limited customization', content: 'The iPhone 16 Pro Max is the ultimate smartphone for those invested in the Apple ecosystem. The A18 Pro chip delivers unmatched single-core performance, the 48MP camera system produces incredible photos with natural colors, and video recording quality is simply the best in the industry. iOS 18 brings Apple Intelligence features that are improving rapidly. At PKR 575,000, it is the most expensive phone on our list, but the resale value, software support, and ecosystem make it worthwhile for many Pakistani buyers.', author: 'PhoneDock Team', published: true },
    { phoneSlug: 'xiaomi-15-ultra', rating: 4.6, pros: 'Best camera phone with Leica, 90W charging, 80W wireless charging, great value', cons: 'Heavy at 227g, HyperOS has bloatware, thick camera bump', content: 'The Xiaomi 15 Ultra is a photography beast. The Leica-tuned quad camera system with a 200MP periscope lens captures stunning shots at any zoom level. The Snapdragon 8 Elite ensures buttery smooth performance, and the 90W charging fills the massive 6000mAh battery in just 35 minutes. At PKR 295,000, it offers nearly the same camera quality as the Samsung S25 Ultra at a significantly lower price point. This is the best camera phone you can buy in Pakistan right now.', author: 'PhoneDock Team', published: true },
    { phoneSlug: 'realme-gt-7-pro', rating: 4.4, pros: 'Incredible battery life (6500mAh), 120W charging, Snapdragon 8 Elite, best for gaming', cons: 'No wireless charging, no IP rating, software needs refinement', content: 'The Realme GT 7 Pro is a gaming powerhouse wrapped in a premium design. The 6500mAh battery is the largest in any flagship phone, easily lasting 2 days of normal use. The Snapdragon 8 Elite handles every game at maximum settings, and the 120W charging takes the battery from 0 to 100% in just 28 minutes. At PKR 175,000, this is the best value flagship in Pakistan for gamers and power users who prioritize battery life above all else.', author: 'PhoneDock Team', published: true },
    { phoneSlug: 'oneplus-13', rating: 4.5, pros: 'Clean OxygenOS, 100W SUPERVOOC, 6000mAh battery, great display', cons: 'Camera not class-leading, design is similar to previous gen', content: 'The OnePlus 13 delivers the flagship experience that OnePlus fans have been waiting for. The Snapdragon 8 Elite, 6000mAh battery, and 100W SUPERVOOC charging create a phone that never runs out of power. OxygenOS 15 is one of the cleanest Android skins available, free from bloatware that plagues Chinese competitors. The 6.82-inch 2K display is gorgeous for media consumption. At PKR 265,000, it is one of the best all-round flagships available in Pakistan.', author: 'PhoneDock Team', published: true },
  ];

  for (const r of reviews) {
    const phone = await db.phone.findUnique({ where: { slug: r.phoneSlug } });
    if (phone) {
      await db.review.upsert({
        where: { id: `review-${r.phoneSlug}` },
        update: r,
        create: { ...r, phoneId: phone.id, id: `review-${r.phoneSlug}` },
      });
    }
  }
  console.log(`✅ ${reviews.length} reviews created`);

  // Prices from stores
  const storePrices = [
    { phoneSlug: 'samsung-galaxy-s25-ultra', storeName: 'Daraz', price: 425000, url: '', inStock: true },
    { phoneSlug: 'samsung-galaxy-s25-ultra', storeName: 'Telemart', price: 420000, url: '', inStock: true },
    { phoneSlug: 'samsung-galaxy-s25-ultra', storeName: 'PriceOye', price: 418000, url: '', inStock: true },
    { phoneSlug: 'iphone-16-pro-max', storeName: 'Daraz', price: 575000, url: '', inStock: true },
    { phoneSlug: 'iphone-16-pro-max', storeName: 'iStuff', price: 570000, url: '', inStock: true },
    { phoneSlug: 'iphone-16-pro-max', storeName: 'PriceOye', price: 565000, url: '', inStock: true },
    { phoneSlug: 'xiaomi-15-ultra', storeName: 'Daraz', price: 295000, url: '', inStock: true },
    { phoneSlug: 'xiaomi-15-ultra', storeName: 'Telemart', price: 290000, url: '', inStock: true },
    { phoneSlug: 'xiaomi-redmi-note-14-pro-plus', storeName: 'Daraz', price: 78000, url: '', inStock: true },
    { phoneSlug: 'xiaomi-redmi-note-14-pro-plus', storeName: 'PriceOye', price: 76000, url: '', inStock: true },
    { phoneSlug: 'realme-gt-7-pro', storeName: 'Daraz', price: 175000, url: '', inStock: true },
    { phoneSlug: 'realme-gt-7-pro', storeName: 'Telemart', price: 172000, url: '', inStock: true },
    { phoneSlug: 'oneplus-13', storeName: 'Daraz', price: 265000, url: '', inStock: true },
    { phoneSlug: 'oneplus-13', storeName: 'PriceOye', price: 260000, url: '', inStock: true },
  ];

  for (const sp of storePrices) {
    const phone = await db.phone.findUnique({ where: { slug: sp.phoneSlug } });
    if (phone) {
      await db.phonePrice.create({
        data: { phoneId: phone.id, storeName: sp.storeName, price: sp.price, url: sp.url, inStock: sp.inStock },
      });
    }
  }
  console.log(`✅ ${storePrices.length} store prices created`);

  console.log('\n🎉 Database seeding complete!');
}

seed().catch(console.error);