import path from 'path';
import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { Brand } from '../src/lib/models/Brand';
import { Phone } from '../src/lib/models/Phone';
import { PhoneSpecs } from '../src/lib/models/PhoneSpecs';
import { PhoneImage } from '../src/lib/models/PhoneSub';
import { PhoneBenchmark } from '../src/lib/models/PhoneSub';
import { CollectedPhone, CollectorSource } from '../src/lib/models/CollectedPhone';
import { validateCollectedPhone, detectDuplicates, suggestCategory, suggestSEO, buildFieldProvenance } from '../src/lib/collectors/services';

const PHONES: Array<{
  brand: string; model: string; pricePKR?: number;
  ptaStatus?: string; featured?: boolean; trending?: boolean; upcoming?: boolean;
  thumbnail?: string; image?: string;
  description?: string; releaseDate?: string;
  display?: string; displayType?: string; resolution?: string;
  refreshRate?: string; protection?: string; brightness?: string;
  chipset?: string; cpu?: string; gpu?: string; process?: string;
  ram?: string; storage?: string; cardSlot?: string;
  mainCamera?: string; selfieCamera?: string;
  aperture?: string; ois?: string; videoRecording?: string;
  battery?: string; charging?: string; wirelessCharge?: string; wirelessSpeed?: string;
  reverseCharge?: string; weight?: string; dimensions?: string;
  build?: string; ipRating?: string; network?: string; fiveG?: string;
  wifi?: string; bluetooth?: string; nfc?: string;
  usb?: string; fingerprint?: string; faceUnlock?: string;
  sensors?: string; colors?: string;
  os?: string; osVersion?: string; osUI?: string;
  updatePolicy?: string; specialFeatures?: string;
  antutu?: number; geekbenchSingle?: number;
  geekbenchMulti?: number; gamingScore?: number;
  pubgFps?: string; codMobileFps?: string; genshinFps?: string;
}> = [];