'use client';
import { readApiResponse } from '@/lib/client/api-response';
import { useCallback, useEffect, useRef, useState } from 'react';
import { RefreshCw, Check, X, ExternalLink, Database, PauseCircle } from 'lucide-react';

type Item={_id:string,status:string,severity:string,[key:string]:any};
type ScanJob={id:string;status:string;totalCount:number;processedCount:number;openedCount:number;withRecommendationCount:number;failedCount:number;progress:number;lastError:string};
type Data={items:Item[];total:number;page:number;pages:number;summary:Record<string,number>;scanJob:ScanJob|null};
type ActionResponse={error?:string;scanJob?:ScanJob};
const EMPTY:Data={items:[],total:0,page:1,pages:1,summary:{},scanJob:null};
const ACTIVE_SCAN=new Set(['queued','running']);
export default function SpecsIntelligencePage(){
 const [data,setData]=useState<Data>(EMPTY); const [loading,setLoading]=useState(true); const [running,setRunning]=useState(''); const [error,setError]=useState(''); const [status,setStatus]=useState('open'); const [page,setPage]=useState(1); const cancelledRef=useRef(false);
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const r=await fetch(`/api/admin/specs-intelligence?status=${status}&page=${page}`,{credentials:'include',cache:'no-store'});const p=await readApiResponse<Data>(r);setData(p);if(!silent)setError('');return p;}catch(e){if(!silent)setError(e instanceof Error?e.message:'Unable to load');return null;}finally{if(!silent)setLoading(false);}},[status,page]);
 useEffect(()=>{void load();},[load]);
 const post=useCallback(async(payload:Record<string,unknown>)=>{const r=await fetch('/api/admin/specs-intelligence',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)});return readApiResponse<ActionResponse>(r);},[]);
 const continueUntilDone=useCallback(async(initial:ScanJob)=>{let job=initial;while(ACTIVE_SCAN.has(job.status)&&!cancelledRef.current){await new Promise(resolve=>setTimeout(resolve,350));const next=await post({action:'continue',jobId:job.id});if(!next.scanJob)break;job=next.scanJob;setData(current=>({...current,scanJob:job}));}await load(true);return job;},[load,post]);
 const runScan=async()=>{cancelledRef.current=false;setRunning('scan');setError('');try{const response=await post({action:'scan',batchSize:25});const scanJob=response.scanJob;if(scanJob){setData(current=>({...current,scanJob}));await continueUntilDone(scanJob);}}catch(e){setError(e instanceof Error?e.message:'Scan failed');await load(true);}finally{setRunning('');}};
 const cancelScan=async()=>{const job=data.scanJob;if(!job)return;cancelledRef.current=true;setRunning('cancel');try{const response=await post({action:'cancel',jobId:job.id});if(response.scanJob)setData(current=>({...current,scanJob:response.scanJob!}));}catch(e){setError(e instanceof Error?e.message:'Unable to cancel scan');}finally{setRunning('');}};
 const run=async(action:string,id?:string)=>{setRunning(id||action);setError('');try{await post({action,id});await load();}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setRunning('');}};
 const scan=data.scanJob; const scanActive=Boolean(scan&&ACTIVE_SCAN.has(scan.status));
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-900"><Database className="h-7 w-7 text-violet-600"/> Specs Intelligence</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Missing specifications are detected in resumable batches of 25 phones. Recommendations only come from the local verified dataset and always require admin approval.</p></div><div className="flex gap-2">{scanActive&&<button onClick={()=>void cancelScan()} disabled={!!running} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold text-slate-700 disabled:opacity-60"><PauseCircle className="h-4 w-4"/>Cancel</button>}<button onClick={()=>void runScan()} disabled={!!running||scanActive} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${running==='scan'||scanActive?'animate-spin':''}`}/>{scanActive?'Scanning…':scan?.status==='failed'?'Retry scan':'Scan now'}</button></div></div>
  {scan&&<div className={`rounded-2xl border p-4 ${scan.status==='failed'?'border-red-200 bg-red-50':scan.status==='completed'?'border-emerald-200 bg-emerald-50':'border-blue-200 bg-blue-50'}`}><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="font-semibold text-slate-900">Scan {scan.status}</div><div className="text-sm text-slate-600">{scan.processedCount} of {scan.totalCount} phones processed · {scan.openedCount} missing fields detected</div></div><div className="text-lg font-bold text-slate-900">{scan.progress}%</div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-blue-600 transition-all" style={{width:`${scan.progress}%`}}/></div>{scan.lastError&&<div className="mt-3 rounded-lg bg-white px-3 py-2 text-sm text-red-700">{scan.lastError}</div>}</div>}
  <div className="grid gap-3 sm:grid-cols-3">{Object.entries(data.summary||{}).map(([k,v])=><div key={k} className="rounded-xl border bg-white p-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{k.replaceAll('_',' ')}</div><div className="mt-1 text-2xl font-bold">{v}</div></div>)}</div>
  <div className="flex items-center gap-2"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="rounded-lg border px-3 py-2 text-sm"><option value="open">Open</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option><option value="all">All</option></select>{error&&<div className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}</div>
  <div className="space-y-3">{loading?<div className="rounded-xl border bg-white p-8 text-center">Loading…</div>:data.items.length===0?<div className="rounded-xl border bg-white p-8 text-center text-slate-500">{scan?.status==='failed'?'The last scan failed. Review the error above and retry.':scanActive?'Scan is still running. Signals will appear as batches complete.':'No signals found.'}</div>:data.items.map(item=><div key={item._id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.severity==='critical'?'bg-red-100 text-red-700':item.severity==='warning'?'bg-amber-100 text-amber-700':'bg-blue-100 text-blue-700'}`}>{item.severity}</span><span className="text-xs text-slate-500">{item.field||item.type}</span></div><h2 className="mt-2 font-semibold text-slate-900">{item.phoneId?.modelName||'Unknown phone'} — {item.field}</h2><p className="mt-1 text-sm text-slate-600">{item.recommendedValue?`Recommended: ${item.recommendedValue}`:'No trusted recommendation yet; manual research required.'}</p><div className="mt-2 text-xs text-slate-500">Confidence {item.confidence||0}%{item.sourceName?` • ${item.sourceName}`:''}{item.sourceUrl&&<a className="ml-2 inline-flex items-center gap-1 text-blue-600" href={item.sourceUrl} target="_blank" rel="noreferrer">Source<ExternalLink className="h-3 w-3"/></a>}</div></div>{item.status==='open'&&<div className="flex gap-2"><button onClick={()=>void run('apply',item._id)} disabled={!!running} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white"><Check className="h-4 w-4"/>Apply</button><button onClick={()=>void run('dismiss',item._id)} disabled={!!running} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-semibold text-slate-700"><X className="h-4 w-4"/>Dismiss</button></div>}</div></div>)}</div>
  <div className="flex items-center justify-between"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Previous</button><span className="text-sm text-slate-500">Page {data.page} of {data.pages}</span><button disabled={page>=data.pages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Next</button></div>
 </div>
}
